language: python
python: "3.9"

install:
  - pip install -e .[ci]

script: make ci

deploy:
  provider: heroku
  app: setup-practice
  api_key:
    secure: $HEROKU_API_KEY
  on:
    branch: main
  run:
    - pip install -e .
    - alembic upgrade head
    - restart
    - flask run

notifications:
  email:
    recipients:
      - kn.golovan@gmail.com
    on_success: never
    on_failure: always
